FROM arm64v8/golang:alpine as build

RUN apk add --no-cache build-base git && \
    wget -O- https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

WORKDIR /go/src/github.com/mhutter/podstalk

COPY . .
RUN dep ensure
RUN go install -v ./cmd/...

FROM arm64v8/alpine

ENV PORT=8080
EXPOSE 8080

COPY --from=build /go/bin/podstalk /bin/podstalk
CMD ["/bin/podstalk"]
