---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podLister
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podListers
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: podLister
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: podstalk
spec:
  selector:
    app: podstalk
  ports:
    - protocol: TCP
      port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podstalk
  labels:
    app: podstalk
spec:
  replicas: 3
  selector:
    matchLabels:
      ds: podstalk
  template:
    metadata:
      labels:
        ds: podstalk
        app: podstalk
    spec:
      containers:
        - name: podstalk
          image: mhutter/podstalk
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SA
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
